//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCajaPopular.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlCliente
    {
        public int IdCliente { get; set; }
        public System.DateTime FechaUltimoMovimiento { get; set; }
        public Nullable<int> TipoUltimoMovimiento { get; set; }
        public Nullable<double> SaldoAnterior { get; set; }
        public Nullable<double> SaldoActual { get; set; }
    }
}
