//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCajaPopular.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int IdMovimiento { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> TipoMovimiento { get; set; }
        public Nullable<double> Monto { get; set; }
        public System.DateTime FechaOperacion { get; set; }
    }
}
