//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaPopularHidalgo.WcfCajaPopular {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/ServicioCajaPopular")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CajaPopularHidalgo.WcfCajaPopular.RespuestaClientes))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaClientes", Namespace="http://schemas.datacontract.org/2004/07/ServicioCajaPopular")]
    [System.SerializableAttribute()]
    public partial class RespuestaClientes : CajaPopularHidalgo.WcfCajaPopular.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CajaPopularHidalgo.WcfCajaPopular.Cliente[] lsClientesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CajaPopularHidalgo.WcfCajaPopular.Cliente[] lsClientes {
            get {
                return this.lsClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.lsClientesField, value) != true)) {
                    this.lsClientesField = value;
                    this.RaisePropertyChanged("lsClientes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ServicioCajaPopular.Modelo")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCajaPopular.ICliente")]
    public interface ICliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/BuscarCliente", ReplyAction="http://tempuri.org/ICliente/BuscarClienteResponse")]
        CajaPopularHidalgo.WcfCajaPopular.RespuestaClientes BuscarCliente(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/BuscarCliente", ReplyAction="http://tempuri.org/ICliente/BuscarClienteResponse")]
        System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.RespuestaClientes> BuscarClienteAsync(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/AgregarCliente", ReplyAction="http://tempuri.org/ICliente/AgregarClienteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CajaPopularHidalgo.WcfCajaPopular.Cliente[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CajaPopularHidalgo.WcfCajaPopular.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CajaPopularHidalgo.WcfCajaPopular.RespuestaClientes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CajaPopularHidalgo.WcfCajaPopular.Response))]
        CajaPopularHidalgo.WcfCajaPopular.Response AgregarCliente(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente, float monto, object mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/AgregarCliente", ReplyAction="http://tempuri.org/ICliente/AgregarClienteResponse")]
        System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.Response> AgregarClienteAsync(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente, float monto, object mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/ModificarCliente", ReplyAction="http://tempuri.org/ICliente/ModificarClienteResponse")]
        CajaPopularHidalgo.WcfCajaPopular.Response ModificarCliente(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/ModificarCliente", ReplyAction="http://tempuri.org/ICliente/ModificarClienteResponse")]
        System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.Response> ModificarClienteAsync(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/EliminarCliente", ReplyAction="http://tempuri.org/ICliente/EliminarClienteResponse")]
        CajaPopularHidalgo.WcfCajaPopular.Response EliminarCliente(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/EliminarCliente", ReplyAction="http://tempuri.org/ICliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.Response> EliminarClienteAsync(int idCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteChannel : CajaPopularHidalgo.WcfCajaPopular.ICliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteClient : System.ServiceModel.ClientBase<CajaPopularHidalgo.WcfCajaPopular.ICliente>, CajaPopularHidalgo.WcfCajaPopular.ICliente {
        
        public ClienteClient() {
        }
        
        public ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CajaPopularHidalgo.WcfCajaPopular.RespuestaClientes BuscarCliente(int idCliente) {
            return base.Channel.BuscarCliente(idCliente);
        }
        
        public System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.RespuestaClientes> BuscarClienteAsync(int idCliente) {
            return base.Channel.BuscarClienteAsync(idCliente);
        }
        
        public CajaPopularHidalgo.WcfCajaPopular.Response AgregarCliente(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente, float monto, object mensaje) {
            return base.Channel.AgregarCliente(DatosCliente, monto, mensaje);
        }
        
        public System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.Response> AgregarClienteAsync(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente, float monto, object mensaje) {
            return base.Channel.AgregarClienteAsync(DatosCliente, monto, mensaje);
        }
        
        public CajaPopularHidalgo.WcfCajaPopular.Response ModificarCliente(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente) {
            return base.Channel.ModificarCliente(DatosCliente);
        }
        
        public System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.Response> ModificarClienteAsync(CajaPopularHidalgo.WcfCajaPopular.Cliente DatosCliente) {
            return base.Channel.ModificarClienteAsync(DatosCliente);
        }
        
        public CajaPopularHidalgo.WcfCajaPopular.Response EliminarCliente(int idCliente) {
            return base.Channel.EliminarCliente(idCliente);
        }
        
        public System.Threading.Tasks.Task<CajaPopularHidalgo.WcfCajaPopular.Response> EliminarClienteAsync(int idCliente) {
            return base.Channel.EliminarClienteAsync(idCliente);
        }
    }
}
